language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm
    - hhvm-nightly

matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm-nightly

branches:
    except:
        - upstream

install:
    - composer install

script: phpunit -c tests/phpunit.xml.dist --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
    hipchat:
        rooms:
            secure: "FAJRDWAojkf5/TXRuFYiRRUfxHeEH0lFcmyYcA2R7bql0BArN2umf0ehNR0R7vynKUerbYzafJ0bzYU0gxvio1Pu2fucy79sHrnGNIqQcVtJVjI88Xuo5QNQq+oOoqQSnHYjRyyK/O2B1qjuEJPZQYDm9yF3Ssw/qqxJzmeKRZU="
        template:
            - >
                Build <a href="%{build_url}">#%{build_number}</a>
                (<a href="%{compare_url}">%{commit}</a>)
                of <a href="https://github.com/%{repository}/tree/%{branch}">%{repository}@%{branch}</a>
                by %{author}: %{message}
        format: html
    slack:
        secure: "POBkaCa5GlK4Bykt/YVaGGn3PtyURBClGRaw6sUPp8fq/Z69h2f4uOyu735bdyacp3zElGqR01wp/5ayO7bvW+hdoSRrVpJsSXRL/OakrRKehBY0mAKtNULVmVmb18lUrVSpyWBRXme1ZSnGgiA+/6Szx2TZuFN9S7q2Qeq8gv4="
